# Generated by Django 4.2.6 on 2023-11-02 07:21

from django.db import migrations, models
import django.db.models.deletion
import django_tuieditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_tuieditor.models.MarkdownField(),
        ),
    ]
