# Generated by Django 4.2.6 on 2023-10-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_email_alter_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='account/%Y/%m/%d/', verbose_name='프로필 사진'),
        ),
    ]
